
PPRROOSSEE OOUUTTPPUUTTSS

_O_p_t_i_o_n_s

     You can request that your document	be compared  against
different standards; typing -t with the	prose command, e.g.,

		     prose -t filename

will compare your text against training	documents.

     A -s option will provide a	very short  version  of	 the
_p_r_o_s_e output.

		     prose -s filename

     If	you already have a style table in a  file,  you	 can
save  time by using it as the input to _p_r_o_s_e rather than the
textfile.  To do this, precede the style table filename	with
a -f, e.g.,

	       prose  -f styletable-filename

     All the options can be selected at	the  same  time	 and
listed in any order.

	     prose -f styletable-filename -s -t

_S_t_a_t_i_s_t_i_c_s


     The table of statistics generated by the program  _s_t_y_l_e
can  be	found in your file styl.tmp.  If you want to look at
it type:

			cat styl.tmp

You can	also use the _m_a_t_c_h program, which provides a  better
format,	type:

		       match styl.tmp

If you are not interested in the file, remove it by typing:

			rm styl.tmp
