CC=mcc
CFLAGS=-g

all:	mtod dtoc showbits view finv

dtoc:	dtoc.c
	mcc $(CFLAGS) -o dtoc dtoc.c

finv:	finv.c
	mcc $(CFLAGS) -o finv finv.c

mtod:	mtod.c
	mcc $(CFLAGS) -o mtod mtod.c

showbits:	showbits.c
	mcc $(CFLAGS) -o showbits showbits.c

view:	view.c
	mcc $(CFLAGS) -o view view.c
