.TH PORT 3X
.SH NAME
port \- mathematical library for Fortran
.SH SYNOPSIS
.B f77
argument ...
.B \-lport
.SH DESCRIPTION
The Port library of hundreds of scientific subroutines
covers approximation,
ordinary differential equations, partial Differential Equations,
linear algebra, optimization and mathematical programming,
quadrature, differentiation, roots, special functions, and
transforms.
It is built upon a framework of service routines for
error handling, stack management, and machine constant parameterization.
.PP
The manual describes the software and gives examples.
.SH SEE ALSO
P. A. Fox,
.I The PORT Mathematical Subroutine Library,
AT&T Bell Laboratories,
May 8, 1984.
.br
P. A. Fox,
.I "The PORT Mathematical Subroutine Library Installation Manual,"
AT&T Bell Laboratories,
September, 1984.
