.TH TOLOWER 3
.SH NAME
tolower, toupper \- force upper or lower case
.SH SYNOPSIS
.B tolower(character)
.PP
.B toupper(character)
.SH DESCRIPTION
If 
.I character 
is an upper case letter,
.I tolower
returns the same lower case letter, otherwise
it returns the original character.
.PP
.I Toupper
does the reverse.
.SH SEE ALSO 
ctype(3)
