OBJ=a.o batcomp.o bomb.o event.o explode.o image.o rock.o ship.o
FILES=a.c batcomp.c bomb.c event.c explode.c image.c rock.c ship.c
BIN=/usr/jerq/bin
CC=3cc
CFLAGS=

a.out:	$(OBJ)
	$(CC) $(CFLAGS) $(OBJ)
clean:
	rm -f *.o core a.out

