.TH DEMO 9.6
.SH NAME
demo \- graphic demonstrations and games
.SH SYNOPSIS
.B demo
[ name ]
.SH DESCRIPTION
If a demo is named,
.I demo
runs it, otherwise
.I demo
produces a list of what's available.
.PP
Games that permit interaction are often controlled by the mouse;
experiment to find out what it does.
Some less obvious interactions are listed below.
.PP
.I Swar
is a two-player game.
One player uses the `asdwx' keys,
the other `12350' keys on the keypad.
.PP
.I Pacman
is controlled by the `hjkl' keys or the mouse.
.SH SEE ALSO
crabs(9.6)
.SH BUGS
Some of the programs don't play fair.
