CC=Ncc
CFLAGS=

SRCS=	c2.h c20.c c21.c
OBJS=	c20.o c21.o index.o

.c.o:
	$(CC) $(CFLAGS) -c $<

c2: $(OBJS)
	$(CC) -o c2 $(OBJS)
	@echo DONE

c20.o c21.o: c2.h

sources:$(SRCS)

$(SRCS):
	sccs get $@

install:	c2
	mv c2 /usr/jerq/lib/mc2

clean:
	-rm $(OBJS) c2
	sccs clean

lint: $(SRCS)
	lint $(SRCS)

print:	$(SRCS)
	pr $? | lpr -c
	touch print
	

