.TH HANG 1
.SH NAME
hang \- start a process in stopped state
.SH SYNOPSIS
.B hang
command
.SH DESCRIPTION
The given command is executed, but stopped before main() is called so that
the process can be picked up by a debugger.
To ensure that breakpoints may be set, the process does not share its text.
.SH SEE ALSO
pi(9.1), kill(1)
