.TH PIC 1
.SH NAME
pic \- troff preprocessor for drawing pictures
.SH SYNOPSIS
.B pic
[
.BI \-T t
]
[
.BI \-D
]
[ files ]
.SH DESCRIPTION
.I Pic
is a
.IR troff (1)
preprocessor for drawing figures on a typesetter.
The basic objects are
.IR box ,
.IR line ,
.IR arrow ,
.IR spline ,
.IR circle ,
.IR ellipse ,
.IR arc ,
and text.
These may be positioned in absolute coordinates or relative to previously
placed objects.
.I Pic
also provides blocks, variables, expressions, built-in functions,
loops, conditionals, and a macro processor.
.PP
The optional argument
.BI \-T t
specifies typesetter
.IR t ;
currently supported typesetters are
.I 202
(the default),
.I cat
(Graphic Systems CAT), and
.I aps
(Autologic APS-5).
.PP
The argument
.BI \-D
causes 
.I pic
to generate
.I troff
commands that draw lines of higher quality.
Recommended for final copy on typesetters.
.SH "SEE ALSO"
B. W. Kernighan,
.I "PIC \(em A Graphics Language for Typesetting"
.br
ideal(1), ped(9.1), doctype(1)
