.TH PWD 1 
.SH NAME
pwd, where \- print machine name and working directory
.SH SYNOPSIS
.B pwd
.PP
.B where
.SH DESCRIPTION
.I Pwd
prints the pathname of the working (current) directory.
.PP
.I Where
prints the name of the machine and the pathname of the
current directory in the form
.IP
machine!fullpathname
.SH "SEE ALSO"
cd(1)
