.TH REV 1 
.SH NAME
rev, revpag \- reverse lines or pages
.SH SYNOPSIS
.B rev
[ file ] ...
.PP
.B revpag
[ option ] ... [ file ] ...
.SH DESCRIPTION
.I Rev 
copies the standard input or the named files to the standard output, reversing
the order of characters in every line.
.PP
.I Revpag
copies the standard input or the named files to the standard output,
reversing the order of the pages.
(The name `\-' means the standard input.)
Options define what constitutes a `page':
.TP "\w'\f3\-o \f2list\f1'+1m"
.BI \-d
flags the input as
.IR troff (1)
output; line counts are ignored.
.TP
.BI \-f
appends a new-page character (014) to the last input page (which is the first
page on the output), if this page is not of the declared length.
.TP
.BI \-l " n"
sets the number of lines per page (66 by default) in the case of
ordinary ASCII input. A new-page character (014) is also recognized
as a page break.
.TP
.BI \-o " list"
produces only pages whose page numbers appear in
the comma-separated
.I list
of numbers and ranges. A `page number' means the ordinal position of a page
in the input. A range
.IR n \- m " means pages " n " through "
.IR m "; a range " \-n " means from the beginning to page " n ;
a range
.I n\-
means from page
.I n
to the end. Numbers and ranges may appear in any order.
.SH SEE ALSO
pr(1), troff(1), xcan(1)
