.TH ADVENTURE 6 local
.SH NAME
adventure, zork, aardvark, rogue, wump \- dungeon-exploration games
.SH SYNOPSIS
.B /usr/games/adventure
.PP
.B /usr/games/zork
.PP
.B /usr/games/aardvark
.PP
.B /usr/games/rogue
.PP
.B /usr/games/wump
.SH DESCRIPTION
.I Adventure 
is the grandaddy of dungeon-exploration games, part
of the object of which is to puzzle out the object and the rules.
.I Zork
marks the zenith of the genre;
.I aardvark
is yet another exemplar.
.PP
.I Rogue
requires a cursor-addressed terminal upon which
appears a map of the cave pursuit.
Indicia published at the bottom of the screen are
the cave level being explored, the amount of gold accumulated,
armor class,
and measures of your potency: `hit points', strength, 
and experience level.
Type `?' for more help.
.PP
The
.I wump
cave is inhabited by a Wumpus and by Super Bats that like to pick you up
and drop you somewhere else.
You wander among the rooms, trying to
shoot the Wumpus with an arrow, meanwhile avoiding
being eaten by the Wumpus and falling
into
Bottomless Pits.
.SH FILES
.nf
/usr/games/lib/ddlrun
/usr/games/lib/aard
adv.susp
rogue.save
/usr/games/lib/rogue_roll
.fi
.SH SEE ALSO
net.games.rogue
.SH BUGS
You take these games where and as you find them.
