.TH SNAKE 6
.SH NAME
snake, worm \- display chase games
.SH SYNOPSIS
.B /usr/games/snake
.PP
.B /usr/games/worm
.SH DESCRIPTION
.I Snake
must be played on 
a HP2621 terminal or equivalent.
The object of the game is to make as much money as possible without
getting eaten by the snake.
.PP
You are represented on the screen by an I.
The snake is 6 squares long and is represented by S's.
The money is $, and an exit is #.
Your score is posted in the upper left hand corner.
.PP
You can move around using
h, j, k, and l keys for left, up, down, and right.
To earn money, move to the same square the money is on.
A new $ will appear when you earn the current one.
As you get richer, the snake gets hungrier.
To leave the game, move to the exit (#).
a
.PP
.I Worm
also requires a 2621-compatible terminal.
Once started, with h, j, k, l keys as for
.I snake,
the worm moves forward unless directed otherwise.
The object is to collect points displayed on the screen
without running into the wall or any part of the worm itself.
The points are added to the worms length.
