.TH TREK 6
.SH NAME
trek, ogre, sol, warp, sail \- war games
.SH SYNOPSIS
.B /usr/games/trek
[ [
.B \-a
] file ]
.PP
.B /usr/games/ogre
.PP
.B /usr/games/sol
.PP
.B /usr/games/warp
.PP
.B /usr/games/sail
.SH DESCRIPTION
.I Trek
is a classic sci-fi game for a dumb terminal.
For instructions, respond `?' to any question.
See the reference for details.
.PP
If a
.I file
is named, a log of the game is written onto that file.
Option
.B \-a
causes the file to be appended to,
not truncated.
.PP
.I Sol
and
.I warp
are other space-war games; they volunteer instructions.
.PP
.I Ogre
is a tank-war game.
It needs a cursor-addressed terminal.
For instructions, see
.IR ogre (6)
on line.
.PP
.I Sail
allows one or more players to con a ship of the line through battle.
It requires a cursor addressed terminal.
See the reference for details.
.SH "SEE ALSO"
/n/bowell/src/doc/trek
.br
/usr/man/man6/ogre.6
.br
/n/bowell/src/doc/sail
