.TH VIEW2D 5
.SH NAME
view2d \- movie of a function f(x, y, t)
.SH DESCRIPTION
Files of this format are produced by
.I view2d(3),
and displayed by commands in
.I view2d(1).
A movie file consists of one or more frames,
each consisting of a header and a sequence
of 16-bit signed integer values for each
pixel, scanned left to right and bottom to top.
(Left-to-right is the inner loop.)
.PP
The header consists of the 32-bit magic number 0135246,
then eight 16-bit integers:
.TP
.B VER
is the version number, currently 3.
.TP
.BR NX ,\  NY
specify the number of pixels in the frame.
These may not vary from frame to frame.
.TP
.BR U ,\ V
relate pixel values
.I p
in the file to user function values
.I f
by
.IP
.I p
=
.I u
+
.IR f /2\(**\(** v.
.TP
.B FIXUV
normally 0;  1 if 
.I U, V, PMIN, PMAX 
of first frame
give a bound on the data in the entire file.
.TP
.BR PMIN ,\  PMAX
limits of the data; only used when 
.IR FIXUV =1.
.LP
and finally a 16-byte ascii representation of a floating point value:
.TP
.B TIME
is a frame index, typically set to simulated time or
to an iteration counter.
This need not be uniformly spaced from frame to frame,
but should be nondecreasing.
.PP
Any pixel value less than -32766 is treated as an
`out of bounds' marker and is not displayed.
Other pixel values lie in the range [-32765,32765].
.SH "SEE ALSO"
view2d(1), view2d(3)
