s/addmag/addmag%%/g
s/submag/submag%%/g
s/fladd/fladd%%/g
s/flcmp/flcmp%%/g
s/fldiv/fldiv%%/g
s/flmul/flmul%%/g
s/flneg/flneg%%/g
s/flsub/flsub%%/g
s/ftol/ftol%%/g
s/itof/itof%%/g
s/ltof/ltof%%/g
s/ultof/ultof%%/g
