.TH CANDEST 7
.SH NAME
candest \- canon laser printers
.SH DESCRIPTION
The names of Canon laser printers, usable in the
.B \-d
option of
.IR can (1)
or as the value of environment variable CANDEST
are:
.PP
.nf
3	3rd floor, end of 9S corridor (mrkos)
4	4th floor, stair 8 (ikeya)
8	3rd floor, stair 8 (tukey)
9	4th floor, stair 9 (wild)
j	jones room (jones)
u	unix room (panther)
/[name]	printer on Datakit machine path (\fIname\fR)
.fi
