.TH FONT 7
.SH NAME
font \- typesetter fonts
.SH DESCRIPTION
The fonts named here may be available on some or all of
the Autologic APS-5 phototypesetter, the Mergenthaler Linotron 202
phototypesetter, the Canon laser printer,
and the Teletype 5620 terminal running under 
.IR mux (9.1).
The names here are those appropriate to
.IR troff (1),
and unless otherwise noted, refer to the 202.
On the 5620 and the Canon there is a separate font for each style and size,
denoted by the
.I troff 
name followed by 
.RB ` . '
and a size, e.g. `CW.11'.
.2C
A1	Avant Garde
A2	Avant Garde italic
A3	Avant Garde bold
A4	Avant Gard bold italic
B	Times bold
B1	Bembo
B2	Bembo italic
B3	Bembo bold
B4	Bembo bold italic
BI	Times bold italic
C	News Gothic condensed (aps-5)
CA	Caslon
CE	Century Expanded (aps-5)
CH	Chess
CI	Century bold italic (aps-5)
CS	Constant Width Slanted
CT	Courier Typewriter (aps-5)
CW	Constant width (ASCII typewriter)
CX	News Gothic condensed italic (aps-5)
E	Eurostyle
EB	Eurostyle bold
EK	Eurostyle black
EX	Eurostyle bold extended
FS	Fraktur and Script
GB	Greek bold (aps-5)
GR	Greek
GS	German Script (aps-5)
H	Helvetica
HB	Helvetica bold
HC	Helvetica condensed
HD	Helvetica bold condensed
HI	Helvetica italic
HJ	Helvetica light italic
HK	Helvetica black
HL	Helvetica light
HO	Helvetica outline
HX	Helvetica bold italic
I	Times italic
K	Baskerville
KB	Baskerville bold
KI	Baskerville italic
KK	Korrina heavy black
KX	Baskerville bold italic
M1	Universal [sic] Math 1
M2	Universal Math 2
M3	Universal Math 3
MB	Memphis bold
MI	Memphis italic
MK	Memphis black
MM	Memphis medium
MX	Memphis bold italic
MZ	Memphis extra bold italic
O	Caslon old
O1	Optima
O2	Optima italic
O3	Optima bold
O4	Optima bold italic
O5	Optima black
OE	Old English
OI	Caslon old italic
OK	Helvetic outline black
PA	Palatino
PB	Palatino bold
PI	Palatino italic
PO	Printout (ASCII constant width)
PX	Palatino bold italic
R	Times Roman
S	Special (math symbols)
S1	Special (aps-5)
SB	Souvenir bold
SC	Script (aps-5)
SI	Souvenir italic
SK	Souvenir black
SM	Stymie medium (aps-5)
SV	Souvenir
SX	Souvenir bold italic
SZ	Souvenir black italic
TB	Techno bold (aps-5)
TX	Techno bold italic (aps-5)
US	United States (202)
X1	Universal Newspaper Pi (202)
.LP
apl
bigblit	Large mux font
chess	Chess pieces for mux
defont	Default mux font
st
texture
tiny	Minimum size mux font
.1C
.SH SEE ALSO
troff(1), can(1), jf(9), font(9)
