.TH LIBRARY 7
.SH NAME
library, bellcat \- bell labs library services
.SH SYNOPSIS
.B library
.PP
.B bellcat
.SH DESCRIPTION
.I Library
places orders with the Bell Labs library network
for books, technical reports, etc.
Its use is self-explanatory.
.PP
.I Bellcat
places a call to the Bell Labs on-line book catalog.
Its use, too, is self-explanatory, except you must use `~.' to exit.
.SH BUGS
.I Bellcat
requires an HP2621 terminal, real or simulated,
and produces some irrelevant chatter.
