CC=/usr/jerq/bin/mcc
AS=/usr/jerq/bin/mas

all:	abs.o atoi.o atol.o cerror.o chrtab.o index.o ldiv.o lmul.o mcount.o muldiv.o oldiv.o qsort.o rand.o rindex.o strcat.o strchr.o strcmp.o strcpy.o strlen.o strncat.o strncmp.o strncpy.o swab.o

clean:
	rm -f *.o
