|define_string(list_type, l0)
|define_counter(level_1, l1)
|define_counter(level_2, l2)
|define_counter(level_3, l3)
|define_counter(level_4, l4)
|define_counter(level_5, l5)
|define_counter(level_6, l6)
|define_counter(level_7, l7)
