|define_string(reference_author, RA)
|define_string(reference_book, RB)
|define_string(reference_location, RC)
|define_string(reference_date, RD)
|define_string(reference_editor, RE)
|define_string(reference_mark, RF)
|define_string(reference_government, RG)
|define_string(reference_institution, RI)
|define_string(reference_journal, RJ)
|define_string(reference_keyword, RK)
|define_string(reference_tm, RM)
|define_string(reference_number, RN)
|define_string(reference_other, RO)
|define_string(reference_page, RP)
|define_string(reference_report, RR)
|define_string(reference_title, RT)
|define_string(reference_volume, RV)

|define_counter(reference_authors, RA)
|define_counter(reference_others, RO)
|define_counter(reference_titles, RT)
|define_counter(reference_pages, RP)

|define_string(reference_begin_definition, R+)
|define_string(reference_other_definition, r0)
|define_string(reference_journal_definition, r1)
|define_string(reference_book_definition, r2)
|define_string(reference_article_definition, r3)
|define_string(reference_report_definition, r4)
|define_string(reference_tm_definition, r5)
|define_string(reference_end_definition, R-)

|define_string(open_double_quote, D+)
|define_string(close_double_quote, D-)
|define_string(open_reference, r+)
|define_string(close_reference, r-)
|define_string(open_period, P+)
|define_string(close_period, P-)
|define_string(open_comma, c+)
|define_string(close_comma, c-)

|define_string(punctation_string, PS)
